version: '3.9'

services:
  db:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data_pg

volumes:
  db-data:


    

