version: '3.9'

services:
  db:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data-pg:/var/lib/postgresql/data_pg
    command: ["postgres", "-c", "listen_addresses='*'"]
    networks:
      - db-net

networks:
  db-net:

volumes:
  db-data-pg:

