version: '3.9'

services:
  db:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - ./backups/backup_a.dmp:/docker-entrypoint-initdb.d/backup_a.dmp
      - ./backups/backup_b.dmp:/docker-entrypoint-initdb.d/backup_b.dmp
    

