version: '3.9'

services:
  pentaho:
    build: ./pentaho
    container_name: pentaho-server
    networks:
      - rede_pentaho
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./data/hsqldb:/opt/pentaho/pentaho-server/data/hsqldb:rw
      - ./data/jackrabbit-repository:/opt/pentaho/pentaho-server/pentaho-solutions/system/jackrabbit/repository:rw
      - ./logs:/opt/pentaho/pentaho-server/tomcat/logs
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - TZ=America/Sao_Paulo

networks:
  rede_pentaho:
    external: true







